name: ward_selection
description: NagarWatch Geofencing Module
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.1.2
  geolocator: ^12.0.0
  flutter_map: ^8.2.2 # Updated flutter_map version
  latlong2: ^0.9.1
  http: ^1.2.2
  flutter_local_notifications: ^18.0.1
  permission_handler: ^11.3.1
  google_fonts: ^6.2.1

flutter:
  uses-material-design: true